/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import { env } from '../../../util/env'

export const getApiHeaders = (): NodeJS.Dict<string> => {
  const token: string = env('API_AUTH_TOKEN')
  return { Authorization: `Bearer ${token}` }
}
