/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

const build = async (): Promise<boolean> => {
  return true
}

export { build }
