/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import { env } from '../../../util/env'
import * as io from '../../../util/io'
import { config } from './config'

const cleanup = async (): Promise<void> => {
  console.info('Cleaning up outdated cache')
  await io.emptyDirectory(config.root)

  const reset = env('RESET_FILE_CACHE')

  if (reset === 'true') {
    console.log('Removing the CDN folder')
    await io.emptyDirectory(config.cdn)
  }
}

export { cleanup }
