/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import path from 'path'

const root = path.join(process.cwd(), 'public', 'cache')
const cdn = path.join(process.cwd(), 'public', 'cdn')

const config = {
  root,
  cdn
}

export { config }
