/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import path from 'path'

import * as io from '../../../util/io'
import { fetchFromApi } from '../fetch'
import { cleanup } from './cleanup'
import { config } from './config'

const start = async (): Promise<void> => {
  try {
    // First fetch data from the API server
    const result = await fetchFromApi()

    // Build filesystem cache
    console.log('Building filesystem cache')
    await cleanup()

    for (const item of result) {
      if (item === null) {
        continue
      }

      const { identifier, data } = item
      const file = path.join(config.root, `${identifier}.json`)

      await io.saveToDisk(file, data)
    }

    console.log('Filesystem cache is now built')
  } catch {
    console.error('Warning: could not reach the API server. Using outdated cache now.')
  }
}

export { start }
