/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import { tasks } from './tasks'

const name = 'Neptune Mutual Integration'

const builder = {
  name,
  hooks: {
    'astro:config:setup': async () => {
      console.time(name)

      for (const task of tasks) {
        const [definition, ...intermediates] = task
        const promises = []

        for (const promise of intermediates) {
          promises.push(promise())
        }

        console.log('Start: %s', definition)
        console.time(definition)
        await Promise.allSettled(promises)
        console.timeEnd(definition)
      }

      console.timeEnd(name)
    }
  }
}

export { builder }
