/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import * as cache from './cache'
import * as media from './media/cache'
import * as syndication from './syndication/index'

const builder = {
  name: 'Neptune Mutual Integration',
  hooks: {
    'astro:config:setup': async () => {
      console.time('API requests took')
      await syndication.sync()
      await cache.start()
      await media.sync()

      console.timeEnd('API requests took')
    }
  }
}

export default builder
