/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import path from 'path'

const root = path.join(process.cwd(), 'public/feeds')

const config = {
  root
}

export { config }
