/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import path from 'path'

import { env } from '../../../util/env'
import {
  emptyDirectory,
  ensureDirectory
} from '../../../util/io'
import { chunkFetch } from './chunk-fetch'
import { getAll } from './docs'

const sync = async (): Promise<void> => {
  const all = await getAll()
  const root = path.join(process.cwd(), 'public', 'cdn')
  await ensureDirectory(root)

  if (env('RESET_FILE_CACHE') === 'true') {
    console.log('Emptying the file cache')
    await emptyDirectory(root)
  }

  const host = env('FILE_URL_PREFIX')

  const files = all.map((x) => {
    const arg: FileDownloadArgs = {
      remote: new URL(x.filename, host).href,
      local: path.join(root, x.filename)
    }

    return arg
  })

  await chunkFetch(files)
}

export { sync }
