/* ----------------------------------------- */
// Do not edit this file
/* ----------------------------------------- */

import path from 'path'

import * as io from '../../../util/io'

const getAll = async (): Promise<Media[]> => {
  const file = path.join(process.cwd(), 'public/cache/media.json')

  if (!await io.exists(file)) {
    return []
  }

  const all = JSON.parse(await io.readFile(file))
  return all.docs
}

export { getAll }
